/*
----------------------------------------------------------
* Nombre: LeadHandler_cls
* Autor Saúl González
* Proyecto: MC - FreewayConsulting
* Descripción : Clase que verifica las reglas de negocio para un lead

* --------------------------------------------------------------------------------
* Versión       Fecha           Autor                   Desripción<p />
* --------------------------------------------------------------------------------
* 1.0           22/02/2021     Saúl González            Creación
* --------------------------------------------------------------------------------
*/

global class LeadHandler_cls {

}